table AIRequestDetail

	column RequestKey
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: RequestKey

	column RequestTimestamp
		dataType: dateTime
		summarizeBy: none
		sourceColumn: RequestTimestamp

	column Status
		dataType: string
		summarizeBy: none
		sourceColumn: Status

	column LatencyMs
		dataType: int64
		summarizeBy: average
		sourceColumn: LatencyMs

	column RetrievedChunkCount
		dataType: int64
		summarizeBy: average
		sourceColumn: RetrievedChunkCount

	column CitationFlag
		dataType: boolean
		summarizeBy: none
		sourceColumn: CitationFlag

	column FeedbackScore
		dataType: int64
		summarizeBy: average
		sourceColumn: FeedbackScore

	column ModelName
		dataType: string
		summarizeBy: none
		sourceColumn: ModelName

	partition AIRequestDetail = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents("C:\TechScope\powerbi\runtime_data\AIRequestDetail.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				ToInt64 = (x as any) as nullable number => if x = null or Text.Trim(Text.From(x)) = "" then null else Int64.From(Number.FromText(Text.From(x))),
				ToLogical = (x as any) as nullable logical => if x = null or Text.Trim(Text.From(x)) = "" then null else let t = Text.Lower(Text.Trim(Text.From(x))) in if t = "true" or t = "1" then true else if t = "false" or t = "0" then false else Logical.From(x),
				ToDateTime = (x as any) as nullable datetime => if x = null or Text.Trim(Text.From(x)) = "" then null else DateTime.FromText(Text.From(x)),
				Typed = Table.TransformColumns(Headers, {
					{"RequestKey", each ToInt64(_), Int64.Type},
					{"RequestTimestamp", each ToDateTime(_), type datetime},
					{"Status", each if _ = null then null else Text.From(_), type text},
					{"LatencyMs", each ToInt64(_), Int64.Type},
					{"RetrievedChunkCount", each ToInt64(_), Int64.Type},
					{"CitationFlag", each ToLogical(_), type logical},
					{"FeedbackScore", each ToInt64(_), Int64.Type},
					{"ModelName", each if _ = null then null else Text.From(_), type text}
				})
			in
				Typed
