table ExecutiveSummary

	measure 'Technology Count' = MAX(ExecutiveSummary[TotalTechnologies])
		formatString: #,0

	measure 'Category Count' = MAX(ExecutiveSummary[Categories])
		formatString: #,0

	measure 'Company Count' = MAX(ExecutiveSummary[Companies])
		formatString: #,0

	measure 'Direct Claims' = MAX(ExecutiveSummary[DirectClaims])
		formatString: #,0

	measure 'Indirect Claims' = MAX(ExecutiveSummary[IndirectClaims])
		formatString: #,0

	measure 'Architecture Layers' = MAX(ExecutiveSummary[ArchitectureLayers])
		formatString: #,0

	measure 'AI Requests' = MAX(ExecutiveSummary[AIRequests])
		formatString: #,0

	measure 'Success Rate' = DIVIDE(MAX(ExecutiveSummary[SuccessfulRequests]), MAX(ExecutiveSummary[AIRequests]))
		formatString: 0.0%

	measure 'Citation Rate' = DIVIDE(MAX(ExecutiveSummary[CitationRequests]), MAX(ExecutiveSummary[AIRequests]))
		formatString: 0.0%

	measure 'Average AI Latency (ms)' = MAX(ExecutiveSummary[AvgLatencyMs])
		formatString: #,0

	column TotalTechnologies
		dataType: int64
		summarizeBy: sum
		sourceColumn: TotalTechnologies

	column Categories
		dataType: int64
		summarizeBy: sum
		sourceColumn: Categories

	column Companies
		dataType: int64
		summarizeBy: sum
		sourceColumn: Companies

	column DirectClaims
		dataType: int64
		summarizeBy: sum
		sourceColumn: DirectClaims

	column IndirectClaims
		dataType: int64
		summarizeBy: sum
		sourceColumn: IndirectClaims

	column ArchitectureLayers
		dataType: int64
		summarizeBy: sum
		sourceColumn: ArchitectureLayers

	column AIRequests
		dataType: int64
		summarizeBy: sum
		sourceColumn: AIRequests

	column SuccessfulRequests
		dataType: int64
		summarizeBy: sum
		sourceColumn: SuccessfulRequests

	column CitationRequests
		dataType: int64
		summarizeBy: sum
		sourceColumn: CitationRequests

	column AvgLatencyMs
		dataType: decimal
		summarizeBy: none
		sourceColumn: AvgLatencyMs

	partition ExecutiveSummary = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents("C:\TechScope\powerbi\runtime_data\ExecutiveSummary.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {
					{"TotalTechnologies", Int64.Type},
					{"Categories", Int64.Type},
					{"Companies", Int64.Type},
					{"DirectClaims", Int64.Type},
					{"IndirectClaims", Int64.Type},
					{"ArchitectureLayers", Int64.Type},
					{"AIRequests", Int64.Type},
					{"SuccessfulRequests", Int64.Type},
					{"CitationRequests", Int64.Type},
					{"AvgLatencyMs", type number}
				})
			in
				Typed
